//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otobus_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesafeler
    {
        public int MesafeId { get; set; }
        public Nullable<int> KalkisSehirId { get; set; }
        public Nullable<int> VarisSehirId { get; set; }
        public Nullable<decimal> MesafeKm { get; set; }
        public Nullable<decimal> TahminiSureSaat { get; set; }
        public Nullable<decimal> UcrefFaktoru { get; set; }
    
        public virtual Sehirler Sehirler { get; set; }
        public virtual Sehirler Sehirler1 { get; set; }
    }
}
