//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otobus_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeKayitlari
    {
        public int OdemeId { get; set; }
        public Nullable<int> BiletId { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public Nullable<decimal> OdemeMiktari { get; set; }
        public string OdemeYontemi { get; set; }
    }
}
