//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otobus_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervasyon()
        {
            this.Koltuklar = new HashSet<Koltuklar>();
        }
    
        public int RezerveId { get; set; }
        public Nullable<int> BiletId { get; set; }
        public Nullable<int> AracId { get; set; }
        public Nullable<int> KoltukId { get; set; }
        public Nullable<int> YolcuId { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<int> SeferId { get; set; }
        public Nullable<System.DateTime> RezerveTarihi { get; set; }
        public string OdemeDurumu { get; set; }
        public Nullable<bool> RezerveDurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Koltuklar> Koltuklar { get; set; }
    }
}
